Update base conversion functions

diff --git a/functions/bin2dec b/functions/bin2dec
--- a/functions/bin2dec
+++ b/functions/bin2dec
@@ -1,17 +1,15 @@
-# Valid with hex numbers starting with or without "0b"
-
 if [ $# -eq 0 ]; then
     echo "Usage: bin2dec (0b)BIN_NUMBER"
     return 1
 fi
 
-# bc doesn't allow lowercase
-local BIN_NUMBER=$(echo "$1" | cut -d'b' -f2 | tr '[:lower:]' '[:upper:]')
+# Binary with/without "0b" prefix or/and grouped
+local BIN_NUMBER=$(echo "$*" | tr -d ' ' | cut -d'b' -f2)
 
 local re='^[0-1]+$'
 if ! [[ $BIN_NUMBER =~ $re ]]; then
-   echo "Error: Not a valid binary number" >&2;
-   return 2
+    echo "Error: Not a valid binary number" >&2;
+    return 2
 fi
 
 echo "obase=10; ibase=2; $BIN_NUMBER" | bc
diff --git a/functions/bin2hex b/functions/bin2hex
--- a/functions/bin2hex
+++ b/functions/bin2hex
@@ -1,16 +1,15 @@
-# Valid with binary numbers starting with or without "0b"
-
 if [ $# -eq 0 ]; then
     echo "Usage: bin2hex (0b)BIN_NUMBER"
     return 1
 fi
 
-local BIN_NUMBER=$(echo "$1" | cut -d'b' -f2)
+# Binary with/without "0b" prefix or/and grouped
+local BIN_NUMBER=$(echo "$*" | tr -d ' ' | cut -d'b' -f2)
 
 local re='^[0-1]+$'
 if ! [[ $BIN_NUMBER =~ $re ]]; then
-   echo "Error: Not a valid binary number" >&2;
-   return 2
+    echo "Error: Not a valid binary number" >&2;
+    return 2
 fi
 
 local REVERSED_BIN=$(echo $BIN_NUMBER | rev)
@@ -41,9 +40,9 @@ done
 
 hex_number=$(echo "$hex_number" | rev)
 
-hex_number=$zeros$hex_number
+local extended_hex_number=$zeros$hex_number
 
 printf "0x%s\n" "$hex_number"
 printf "%s\n" "$hex_number"
-# printf "%s\n" "$(echo $hex_number | rev | sed -r 's/(.{4})/\1 /g' | rev)"
-printf "%s\n" "$(echo "$hex_number" | sed -r 's/(.{4})/\1 /g')"
+# printf "%s\n" "$(echo $extended_hex_number | rev | sed -r 's/(.{4})/\1 /g' | rev)"
+printf "%s\n" "$(echo "$extended_hex_number" | sed -r 's/(.{4})/\1 /g')"
diff --git a/functions/dec2hex b/functions/dec2hex
--- a/functions/dec2hex
+++ b/functions/dec2hex
@@ -7,8 +7,8 @@ local DEC_NUMBER=$1
 
 local re='^[0-9]+$'
 if ! [[ $DEC_NUMBER =~ $re ]]; then
-   echo "Error: Not a valid decimal number" >&2;
-   return 2
+    echo "Error: Not a valid decimal number" >&2;
+    return 2
 fi
 
 local hex_number=$(echo "obase=16; ibase=10; $DEC_NUMBER" | bc)
@@ -25,9 +25,9 @@ for i in $(seq 1 $((total_bytes - bytes_number))); do
     zeros+="0"
 done
 
-hex_number=$zeros$hex_number
+local extended_hex_number=$zeros$hex_number
 
 printf "0x%s\n" "$hex_number"
 printf "%s\n" "$hex_number"
-# printf "%s\n" "$(echo $hex_number | rev | sed -r 's/(.{4})/\1 /g' | rev)"
-printf "%s\n" "$(echo "$hex_number" | sed -r 's/(.{4})/\1 /g')"
+# printf "%s\n" "$(echo $extended_hex_number | rev | sed -r 's/(.{4})/\1 /g' | rev)"
+printf "%s\n" "$(echo "$extended_hex_number" | sed -r 's/(.{4})/\1 /g')"
